### ISSUE TITLE
code pattern

### ISSUE THREAD

**Issue by ionutzp** [tregoning/photoTilt#5]
hi, there's no need to use new when you create a new instance of a phototilt

var photoTilt = PhotoTilt({
    url: 'photo.jpg',
    lowResUrl: 'lowRes.jpg', //optional it will load lowRes 1st if available
    maxTilt: 18, //optional, defaults to 20
    container: document.body  //optional, defaults to body
    reverseTilt: false //optional, defaults to false
});

**Comment by tregoning** [comment]
Hi ionutzp,

You are correct. Currently there is no need as the codebase does not use 'this' anywhere.  
However, it is possible that the codebase will do in the future (after some refactoring) and I would like to not have breaking changes.

Cheers
