### ISSUE TITLE
Graceful degradation for desktops?

### ISSUE THREAD

**Issue by zshannon** [tregoning/photoTilt#7]
It'd be great if this could degrade to following the pointer location on devices without touch screens. Would you accept a PR implementing that?

**Comment by tregoning** [comment]
Hi zshannon,

Thanks for the suggestion, I'll like to see it. But to me, the whole point of the tilt is to free/enable the ability to swipe left/right to move between photos.

On a non-touch device, 1st is likely to be in landscape mode already and further we have hover state , scrollbars etc, so it will be almost an anti-pattern.

Having said that, if you do make it, please let me know I'll like to play with it

Cheers

JT
